spring:
  rabbitmq:
    host: 192.168.228.128
    port: 5672
    username: admin
    password: admin
    #虚拟host 可以不设置,使用server默认host
    virtual-host: /
    #确认消息已发送到交换机(Exchange)
    #publisher-confirms: true
    publisher-confirm-type: correlated
    #确认消息已发送到队列(Queue)
    publisher-returns: true
#    listener:
#      simple:
#        batch-size: 10

    # 动态创建和绑定队列、交换机的配置
    modules:
      # 延时队列，到了过期的时间会被转发到订单死信队列
      - exchange:
          name: log.exchange
          type: DIRECT
        queue:
          name: log.inbound.operation.queue
          #          dead-letter-exchange: order.exchange
          #          dead-letter-routing-key: order.close.routing.key
          arguments:
            # 1分钟(测试)，单位毫秒
            x-message-ttl: 60000
        routing-key: log.inbound.operation.queue.key

      - exchange:
          name: demo.test
          type: DIRECT
        queue:
          name: demo.test
          #          dead-letter-exchange: order.exchange
          #          dead-letter-routing-key: order.close.routing.key
          arguments:
            # 1分钟(测试)，单位毫秒
            x-message-ttl: 60000
        routing-key: demo.test

      - exchange:
          name: demo.batch
          type: DIRECT
        queue:
          name: batch.test
          #          dead-letter-exchange: order.exchange
          #          dead-letter-routing-key: order.close.routing.key
          arguments:
            # 1分钟(测试)，单位毫秒
            x-message-ttl: 60000
        routing-key: batch.test
