server:
  port: 8070


spring:
  application:
    name: service-gateway

  cloud:
    nacos:
      discovery:
        namespace: public
        server-addr: 101.43.86.27:8848
        username: nacos
        password: nacos

    gateway:
      discovery:
        locator:
          enabled: true # ???????????????????????????"
          routes:
            id: service-openfeign  #payment_routh #???ID?????????????????????
            #uri: http://localhost:8761  #???????????? ????????
            uri: lb://service-openfeign #????????????-------????????????? lb://???eureka???????
            predicates:
              - Path=/service-openfeign/** #?????????????--------??????????????/servero1/**????????uri
#            filters: #?????
#              - StripPrefix=0  #  ??/name/bar/foo??????????????????????????/foo-----????????????????????????????url?????