spring:
  application:
    name: service-stock

  cloud:
    inetutils:
      preferredNetworks:
        - 192.168
        - 10.0
    nacos:
      discovery:
        namespace: public
        server-addr: 101.43.86.27:8848
        username: nacos
        password: nacos


server:
  port: 8030












