spring:
  application:
    name: service-stock

  cloud:
    nacos:
      discovery:
        namespace: public
        server-addr: 101.43.86.27:8848
        username: nacos
        password: nacos


server:
  port: 8030












