server:
  port: 8040

spring:
  application:
    name: service-order

  cloud:
    nacos:
      discovery:
        namespace: public
        server-addr: 101.43.86.27:8848
        username: nacos
        password: nacos
#   loadbalancer:
#     ribbon:
#       enabled: false













